// common/messageTypes.js
export const MESSAGE_TYPES = {
  INIT_PORT: "INIT_PORT",
  PAGE_LOADED: "PAGE_LOADED",
  TAB_UPDATED: "TAB_UPDATED",
  TAB_ACTIVATED: "TAB_ACTIVATED",
  CONTENT_SCRIPT_FUNCTION: "CONTENT_SCRIPT_FUNCTION",
  BACKGROUND_FUNCTION: "BACKGROUND_FUNCTION",
  BACKGROUND_FUNCTION_RESPONSE: "BACKGROUND_FUNCTION_RESPONSE",
  // Add more as needed
}

export const PORT_NAMES = {
  BACKGROUND: "BACKGROUND_PORT",
  SIDEPANEL: "SIDEPANEL_PORT",
  GMAIL_SCRIPT: "GMAIL_SCRIPT_PORT",
  DRIVE_SCRIPT: "DRIVE_SCRIPT_PORT",
}
